apiVersion: v1
kind: Namespace
metadata:
  name: cnpg3
---

apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example2
  namespace: cnpg3
spec:
  instances: 2

  storage:
    size: 1Gi